### ISSUE TITLE
move to organization ?

### ISSUE THREAD

**Issue by arsenovic** [pygae/clifford#11]
minor organization  questions for https://github.com/pygae. 

@hugohadfield, @moble, @tingelst,

1. i had a hard time to come up with a name. is the name agreeable?
2. should i *move* the clifford repo to pygae, instead of fork it? 
3. would it make sense to do the same for pyversor?

**Comment by arsenovic** [comment]
ok, sounds like the name is universally loved. 
i think i will move the clifford repo to pygae.
@hugohadfield, i think this will blow away your recent changes,  i am not sure the easiest  way to re-add your changes. are you a git magician?

**Comment by hugohadfield** [comment]
@arsenovic name is fine by me, I agree its probably best to move this repo to pygae, I'm unfortunately not a git magician, don't worry about my changes I'll just rebranch the repo and put them in from my local copy

**Comment by arsenovic** [comment]
sounds good.
