### ISSUE TITLE
Get pypi release working

### ISSUE THREAD

**Issue by hugohadfield** [pygae/clifford#121]
We should be automatically releasing to pypi when the travis builds succeed but as the builds have been broken for a while we have had a release. As there are quite a few improvements etc to the clifford package since the last release we should make sure to do this soon

**Comment by eric-wieser** [comment]
I assume that this is already working, and all we have to do is push a tag?

**Comment by arsenovic** [comment]
https://github.com/pygae/clifford/blob/master/.travis.yml#L34 
i think so

**Comment by hugohadfield** [comment]
So the conda release is 1.0.5 https://anaconda.org/conda-forge/clifford/files
Pypi is 1.0.4
I guess we will do 1.0.6? What do you guys think we should do about the missing 1.0.5?

**Comment by eric-wieser** [comment]
We could do a manual upload of https://github.com/pygae/clifford/tree/v1.0.5 if we care

**Comment by arsenovic** [comment]
i doubt anyone used that function

**Comment by hugohadfield** [comment]
I say lets bump to 1.1.0, to celebrate Eric joining the team! (and because hes running clifford through a pretty comprehensive overhaul..)

**Comment by eric-wieser** [comment]
Looks like this [is indeed broken](https://travis-ci.org/pygae/clifford/jobs/603923692#L698-L791):
```
Installing deploy dependencies
Authenticated as arsenovic
dpl.2
Preparing deploy
dpl.3
Deploying application
clifford.egg-info/PKG-INFO already exists, no checkout
clifford.egg-info/SOURCES.txt already exists, no checkout
clifford.egg-info/dependency_links.txt already exists, no checkout
clifford.egg-info/requires.txt already exists, no checkout
clifford.egg-info/top_level.txt already exists, no checkout
Could not restore untracked files from stash entry
PyPI upload failed.
failed to deploy
```

**Comment by eric-wieser** [comment]
Closing, this is basically working, and the remainder is tracked in #179
