### ISSUE TITLE
Changing Backends

### ISSUE THREAD

**Issue by arsenovic** [pygae/clifford#13]
One feature which might be of interest could be support for multiple computational backends. 

here is a toy example to demo the idea that  i made a while ago. 

https://gist.github.com/arsenovic/125cb38cbfe3008e5f417b18267c845d

**Comment by aeoost** [comment]
@arsenovic What about GPU-accelerated deep learning backends like Tensorflow, PyTorch, CNTK?

**Comment by arsenovic** [comment]
i dont know what a deep learning backend  for GA would mean. 
you could use GA in deep learning modules, but that is kind of the other way around. 

this demo was more to show that adopting a consistent  high-level API  would allow python to act like a GA pseudo-code.  however,  i dont think this concept would scale to complex or high performance applications.

**Comment by aeoost** [comment]
@arsenovic What I had in mind was something similar to how Pyro (http://pyro.ai/ , a probabilistic programming language) is built on top of PyTorch. I understand what you mean about it being the wrong way around. Maybe it is not the goal of the Clifford project, it’s just what I personally am looking for (a way to use geometric algebra in GPU-accelerated neural nets).

**Comment by hugohadfield** [comment]
On this note I have played around with a range of different GPU accelerated backends including tensorflow, pytorch and have so far found that the best results come from using  numba.cuda combined with a custom code generator. This will probably be rolled into clifford.tools at some point in the vaguely near future when I find time... I definitely like the idea of compatibility with other tools, it would be interesting to see how the speed of the library compares with @tingelst 's pyversor!

**Comment by hugohadfield** [comment]
@arsenovic I think we should close this for now, it is useful but probably not a core focus of the library? Would definitely make a nice demo to show how similar the syntax between the two libraries is though etc

**Comment by arsenovic** [comment]
yes, i would say this can be removed as it is impractical except for simplest demos.
