### ISSUE TITLE
Remove `auto_version`

### ISSUE THREAD

**Issue by eric-wieser** [pygae/clifford#171]
We don't seem to be using this for anything other than its conda bootstrapping via `travis_install_conda.sh`.

@moble, I assume it was you that added this - can you put forth an argument for keeping it?

If not, I'll go ahead and delete it.

Relates to #45

**Comment by moble** [comment]
I think it was @arsenovic who added this, actually.  Especially since so much work has happened lately on CI, I won't even attempt an argument, and will gladly defer to your judgment on deleting it.  Certainly the versioning stuff is irrelevant, since `clifford` is semantically versioned.
