### ISSUE TITLE
cga.Round.radius is always 1

### ISSUE THREAD

**Issue by eric-wieser** [pygae/clifford#184]
```python
>>> from clifford.cga import CGA
>>> cga = CGA(3)
>>> r = cga.round()
>>> r.radius
1
```

**Comment by pavlo-melnyk** [comment]
In the `radius` property of the `Round` class, there is a `=` missing after `dual_sphere / ` [here](https://github.com/pygae/clifford/blob/67ea8ae7b7b8004c4c8322949918d96b00e87fa7/clifford/cga.py#L305), thus not updating `dual_sphere`.

I believe it should be

    def radius(self):
        '''
        radius of the round (a float)
        '''
        dual_sphere = self.dual
        dual_sphere /= (-dual_sphere | self.cga.einf)
        return math.sqrt(abs(dual_sphere * dual_sphere)

**Comment by arsenovic** [comment]
looks right. you make a pr?

**Comment by arsenovic** [comment]
also, maybe we should put a disclaimer on cga,  describing it as a 'sandbox' module for now?

**Comment by pavlo-melnyk** [comment]
I've just made a pr
