### ISSUE TITLE
How to get more accurate caculation?

### ISSUE THREAD

**Issue by codetaobeibei** [pygae/clifford#22]
Hi, 
I am using clifford for mathematical computation of conformal geometric algebra. I want to get the angle between two planes, but the caculated output has only 5 number after decimal point. For example, we can use inner product to caculate the angle between plane one and plane two, if the angle is 30 degree,the answer caculated is 29.999473308300235-not acurate enough. So, how can I get more accurate caculation?
The code is below, as I am new to clifford, I am not sure the code below for the caculation whether true or not.The IDE is  jupyter notebook.
Thank you
```
import numpy as np
from clifford import Cl, conformalize
G2,blades_g2=Cl(3)
G3c,blades_g3c,stuff=conformalize(G2)
locals().update(blades_g3c)
locals().update(stuff)
I = eo^e1^e2^e3^einf
plane0 = 1*e2+1*einf
p0 = up(eo)
p1=up(np.sqrt(3)/2*e1+0.5*e2)
p2=up(e3)
plane1=p0^p1^p2^einf
plane1.normal()
plane0_star = plane0*I.inv()
plane0_star|plane1/(abs(plane0)*abs(plane1))  #the answer is 0.86603,can this be more accurate?
np.arccos(0.86603) *180/pi  # the answer is 29.999473308300235
```

**Comment by hugohadfield** [comment]
import numpy as np
from clifford import Cl, conformalize
G2,blades_g2=Cl(3)
G3c,blades_g3c,stuff=conformalize(G2)
locals().update(blades_g3c)
locals().update(stuff)
I = eo^e1^e2^e3^einf
plane0 = 1*e2+1*einf
p0 = up(eo)
p1=up(np.sqrt(3)/2*e1+0.5*e2)
p2=up(e3)
plane1=p0^p1^p2^einf
plane1.normal()
plane0_star = plane0*I.inv()
ans = plane0_star|plane1/(abs(plane0)*abs(plane1)) 
print( np.arccos(ans[0]) *180/np.pi)

This now gives 29.999999999999993
By printing to 0.86603 you have lost huge amounts of accuracy compared to just using the double natively

**Comment by arsenovic** [comment]
@codetaobeibei  , does hugo's answer  make sense to you ?

**Comment by codetaobeibei** [comment]
Yes, thanks for your help, the accuracy of the answer is actually what I need!
