### ISSUE TITLE
Pypi version bump

### ISSUE THREAD

**Issue by hugohadfield** [pygae/clifford#27]
Could we bump the version in pypi to the latest in master?

**Comment by arsenovic** [comment]
yeah, you want me to do that?
eventually we should put this on conda-forge.

**Comment by hugohadfield** [comment]
That would be great, I'd happily do it myself but don't know how! Definitely keen to put it up on conda-forge.

**Comment by arsenovic** [comment]
we can do this,  https://docs.travis-ci.com/user/deployment/pypi/

this way when you push a tag it will make a automatically make release and upload to pypi. however if you mess something up, then you cannot re-upload a new release of the same vesion#, fyi. i hate pypi for this reason. 

also currently this is hosted under arsenovic on pypi, which is fine with me.

**Comment by hugohadfield** [comment]
Oops looks like I failed to push my local tag.. Now in meetings etc will finish the release when I'm back at my desk this afternoon

**Comment by hugohadfield** [comment]
hmm, latest build error when I push my tags is this:
``copying clifford.egg-info/SOURCES.txt -> clifford-0.82/clifford.egg-info
copying clifford.egg-info/dependency_links.txt -> clifford-0.82/clifford.egg-info
copying clifford.egg-info/requires.txt -> clifford-0.82/clifford.egg-info
copying clifford.egg-info/top_level.txt -> clifford-0.82/clifford.egg-info
Writing clifford-0.82/setup.cfg
creating dist
Creating tar archive
removing 'clifford-0.82' (and everything under it)
Uploading distributions to https://upload.pypi.org/legacy/
Uploading clifford-0.82.tar.gz

  0% 0.00/27.0k [00:00<?, ?B/s]
100% 27.0k/27.0k [00:00<00:00, 107kB/s]
HTTPError: 403 Client Error: Invalid or non-existent authentication information. for url: https://upload.pypi.org/legacy/

travis_fold:end:dpl.3
clifford.egg-info/PKG-INFO already exists, no checkout
clifford.egg-info/SOURCES.txt already exists, no checkout
clifford.egg-info/dependency_links.txt already exists, no checkout
clifford.egg-info/requires.txt already exists, no checkout
clifford.egg-info/top_level.txt already exists, no checkout
Could not restore untracked files from stash entry
PyPI upload failed.
failed to deploy
awk 'NR==FNR{a[$1]++;next};!($1 in a)' $TRAVIS_TMPDIR/pids_{before,after}
``

**Comment by arsenovic** [comment]
ok i updated the credentials try it again (pulling master, re-tag, and  push (with tags))

**Comment by hugohadfield** [comment]
v0.82 is officially released!
