### ISSUE TITLE
AGACSE release

### ISSUE THREAD

**Issue by hugohadfield** [pygae/clifford#32]
I have just bumped the version number to v0.83 to test how the latest tools work with GAOnline etc and to check they work on Azure/other online notebooks.... It would be good to do a better release for AGACSE (I'm gonna start writing doc strings now :)), not really sure how versioning numbers should work but looking at this: https://semver.org/ we might want to make it v0.90 or maybe we bump to v1.0...

Either way it would be good to release by the end of the week!

**Comment by moble** [comment]
As a somewhat neutral observer, IMO a bump to 1.0 seems appropriate.  In the semver FAQ it says this:

> How do I know when to release 1.0.0?
> 
> If your software is being used in production, it should probably already be 1.0.0. If you have a stable API on which users have come to depend, you should be 1.0.0. If you’re worrying a lot about backwards compatibility, you should probably already be 1.0.0.

All these things seem true to me.  You've made a lot of important changes lately; on the other hand it looks like everything is still very much usable — so it seems like time for more than a minor incremental bump.  Plus, if you're going to be advertising the package at AGACSE, it will always attract more attention if you're able to say that you're making a 1.0 release.

One thing that might be good before making the bump would be to look through the issues to see if there are any that could be easily closed.  In particular, I wonder if you guys have anything more to say about #3, #10, #15, and #17 after these changes.

**Comment by hugohadfield** [comment]
@moble I think you are right, bumping to 1.0.0 makes the most sense and this is probably a good point to take stock and see what we can close/what we want to prioritise for the future etc!

**Comment by hugohadfield** [comment]
Ok I am going to push the latest version from master out as a v1.0.0!
