### ISSUE TITLE
Consider deprecating `MultiVector.__len__`

### ISSUE THREAD

**Issue by eric-wieser** [pygae/clifford#344]
Today, `len(mv)` returns `mv.layout.gaDims`. I think we should deprecate this behavior because:

* It's not used frequently enough for the short spelling to be worthwhile
* It doesn't generalize well to treating N-multivectors as a subspace of (N+1)-multivectors
* In conjunction with `__getitem__`, it allows `list(mv)` which isn't mathematically meaningful (it exposes internal information), and is much slower than `mv.value`.
* If the user is using it exactly because they want implementation details, they can just use `len(mv.value)`.
* `len(mv_array)` must have a different and unrelated meaning

**Comment by hugohadfield** [comment]
I support this for sure

**Comment by arsenovic** [comment]
i agree with this.

**Comment by hugohadfield** [comment]
Just found an example of code reliant on len(mv) in the wild, our own pyganja:
https://github.com/pygae/pyganja/blob/19849957dfba5f9f0b558c072fb7dfd783db9f0d/pyganja/GanjaScene.py#L46

**Comment by hugohadfield** [comment]
Hopefully now removed the use of the above via https://github.com/pygae/pyganja/pull/45
