### ISSUE TITLE
Documentation: Missing link to installation instructions

### ISSUE THREAD

**Issue by corcoted** [pygae/clifford#375]
I noticed that the installation instructions were hard to find.  I was able to trace that problem to a broken link in `doc/index.rst`.  I also noticed there were no installation instructions in `README.md`, but maybe that was intentional.

At any rate, I made those two small changes and submitted PR #374

**Comment by hugohadfield** [comment]
Closing as we have now merged https://github.com/pygae/clifford/pull/374 , thanks again for the PR Ted
