### ISSUE TITLE
Installation issue... Jupyter Notebook

### ISSUE THREAD

**Issue by charpelletier** [pygae/clifford#415]
I don't know what i'm doing wrong...Looking forward to play with it...
!python -V
Python 3.7.4
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
```
from clifford.g3 import * 

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
TypeError: expected dtype object, got 'numpy.dtype[bool_]'

The above exception was the direct cause of the following exception:

SystemError                               Traceback (most recent call last)
<ipython-input-3-d4101a335cb8> in <module>
----> 1 from clifford.g3 import *

C:\ProgramData\Anaconda3\lib\site-packages\clifford\g3.py in <module>
      1 from . import Cl
----> 2 layout, blades = Cl(3)
      3 locals().update(blades)

C:\ProgramData\Anaconda3\lib\site-packages\clifford\__init__.py in Cl(p, q, r, sig, names, firstIdx, mvClass)
    731     """
    732     if sig is None:
--> 733         layout = Layout._from_Cl(p, q, r, firstIdx=firstIdx, names=names)
    734     else:
    735         layout = Layout._from_sig(sig, firstIdx=firstIdx, names=names)

C:\ProgramData\Anaconda3\lib\site-packages\clifford\_layout.py in _from_Cl(cls, p, q, r, **kwargs)
    161     def _from_Cl(cls, p=0, q=0, r=0, **kwargs):
    162         """ Factory method from a ${Cl}_{p,q,r}$ notation """
--> 163         return cls._from_sig([0]*r + [+1]*p + [-1]*q, **kwargs)
    164 
    165     def __hash__(self):

C:\ProgramData\Anaconda3\lib\site-packages\clifford\_layout.py in _from_sig(cls, sig, firstIdx, **kwargs)
    156         bladeTupList = cf.elements(len(sig), firstIdx)
    157 
--> 158         return cls(sig, bladeTupList, firstIdx=firstIdx, **kwargs)
    159 
    160     @classmethod

C:\ProgramData\Anaconda3\lib\site-packages\clifford\_layout.py in __init__(self, sig, bladeTupList, firstIdx, names)
    144                 (len(names), self.gaDims))
    145 
--> 146         self._genTables()
    147         self.adjoint_func = get_adjoint_function(self.gradeList)
    148         self.left_complement_func = self._gen_complement_func(wedge=lambda a, b: a^b)

C:\ProgramData\Anaconda3\lib\site-packages\clifford\_layout.py in _genTables(self)
    309             self.linear_map_to_bitmap,
    310             self.bitmap_to_linear_map,
--> 311             self.sig
    312         )
    313         self.omt = sparse.where(omt_prod_mask, self.gmt, self.gmt.dtype.type(0))

C:\ProgramData\Anaconda3\lib\site-packages\clifford\__init__.py in construct_tables(gradeList, linear_map_to_bitmap, bitmap_to_linear_map, signature)
    145     # wrap the numba one
    146     indices, *arrs = _numba_construct_tables(
--> 147         gradeList, linear_map_to_bitmap, bitmap_to_linear_map, signature
    148     )
    149     dims = len(gradeList)

SystemError: CPUDispatcher(<function _numba_construct_tables at 0x0000023C7FDF6318>) returned a result with an error set
```

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
Below is an other try through Binder:
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

```
from clifford.g3 import * 

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
TypeError: expected dtype object, got 'numpy.dtype[bool_]'

The above exception was the direct cause of the following exception:

SystemError                               Traceback (most recent call last)
<ipython-input-3-d4101a335cb8> in <module>
----> 1 from clifford.g3 import *

C:\ProgramData\Anaconda3\lib\site-packages\clifford\g3.py in <module>
      1 from . import Cl
----> 2 layout, blades = Cl(3)
      3 locals().update(blades)

C:\ProgramData\Anaconda3\lib\site-packages\clifford\__init__.py in Cl(p, q, r, sig, names, firstIdx, mvClass)
    731     """
    732     if sig is None:
--> 733         layout = Layout._from_Cl(p, q, r, firstIdx=firstIdx, names=names)
    734     else:
    735         layout = Layout._from_sig(sig, firstIdx=firstIdx, names=names)

C:\ProgramData\Anaconda3\lib\site-packages\clifford\_layout.py in _from_Cl(cls, p, q, r, **kwargs)
    161     def _from_Cl(cls, p=0, q=0, r=0, **kwargs):
    162         """ Factory method from a ${Cl}_{p,q,r}$ notation """
--> 163         return cls._from_sig([0]*r + [+1]*p + [-1]*q, **kwargs)
    164 
    165     def __hash__(self):

C:\ProgramData\Anaconda3\lib\site-packages\clifford\_layout.py in _from_sig(cls, sig, firstIdx, **kwargs)
    156         bladeTupList = cf.elements(len(sig), firstIdx)
    157 
--> 158         return cls(sig, bladeTupList, firstIdx=firstIdx, **kwargs)
    159 
    160     @classmethod

C:\ProgramData\Anaconda3\lib\site-packages\clifford\_layout.py in __init__(self, sig, bladeTupList, firstIdx, names)
    144                 (len(names), self.gaDims))
    145 
--> 146         self._genTables()
    147         self.adjoint_func = get_adjoint_function(self.gradeList)
    148         self.left_complement_func = self._gen_complement_func(wedge=lambda a, b: a^b)

C:\ProgramData\Anaconda3\lib\site-packages\clifford\_layout.py in _genTables(self)
    309             self.linear_map_to_bitmap,
    310             self.bitmap_to_linear_map,
--> 311             self.sig
    312         )
    313         self.omt = sparse.where(omt_prod_mask, self.gmt, self.gmt.dtype.type(0))

C:\ProgramData\Anaconda3\lib\site-packages\clifford\__init__.py in construct_tables(gradeList, linear_map_to_bitmap, bitmap_to_linear_map, signature)
    145     # wrap the numba one
    146     indices, *arrs = _numba_construct_tables(
--> 147         gradeList, linear_map_to_bitmap, bitmap_to_linear_map, signature
    148     )
    149     dims = len(gradeList)

SystemError: CPUDispatcher(<function _numba_construct_tables at 0x0000023C7FDF6318>) returned a result with an error set
```
1

​

1

**Comment by MasterJames** [comment]
You followed the detailed instruction with python 3.7.4 is greater then the requirement 3.5.?

https://clifford.readthedocs.io/en/latest/installation.html

Is your numpy and jbook all up to date?

**Comment by eric-wieser** [comment]
What version of `numba` do you have installed?

**Comment by charpelletier** [comment]
Numpy :  1.21.2
Numba : 0.45.1
Jupyter notebook : 6.0.1
Jupyter core : 4.5.0

De : Eric Wieser ***@***.***>
Envoyé : 6 octobre 2021 04:40
À : pygae/clifford ***@***.***>
Cc : Pelletier, Charles ***@***.***>; Author ***@***.***>
Objet : Re: [pygae/clifford] Installation issue... Jupyter Notebook (#415)

Avertissement automatisé: Ce courriel provient de l'extérieur de notre organisation. Ne cliquez pas sur les liens et les pièces jointes si vous ne reconnaissez pas l'expéditeur.


What version of numba do you have installed?

-
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fpygae%2Fclifford%2Fissues%2F415%23issuecomment-935757278&data=04%7C01%7Ccharles.pelletier%40transports.gouv.qc.ca%7Cc7c16cbd5c6f48c4230108d988a4d34f%7Ca6a092a9b59a42c4a3a11e695a8701f5%7C0%7C0%7C637691063774900861%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=IQnsFbUGZGQMKG1rNGjVMwbLCwoIMQmDgl9NIB2ANwQ%3D&reserved=0>, or unsubscribe<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAQEF3SGD4524U62FK2JJQXTUFQDMNANCNFSM5FMVFZYQ&data=04%7C01%7Ccharles.pelletier%40transports.gouv.qc.ca%7Cc7c16cbd5c6f48c4230108d988a4d34f%7Ca6a092a9b59a42c4a3a11e695a8701f5%7C0%7C0%7C637691063774900861%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=GekwhviD%2Bi9XN7PeGPojT68xpOXR0LQJ%2BUhkdYg0IYc%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Ccharles.pelletier%40transports.gouv.qc.ca%7Cc7c16cbd5c6f48c4230108d988a4d34f%7Ca6a092a9b59a42c4a3a11e695a8701f5%7C0%7C0%7C637691063774910863%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=U1dHccuHjJXh94JqmaOiYUTC0c3HQ0AzIPSr1kLvsnA%3D&reserved=0> or Android<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Ccharles.pelletier%40transports.gouv.qc.ca%7Cc7c16cbd5c6f48c4230108d988a4d34f%7Ca6a092a9b59a42c4a3a11e695a8701f5%7C0%7C0%7C637691063774910863%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=C0JR7z4CPMoEG%2BvvvRPhA%2B9iOsrnfFVDlM%2FKsrxwW04%3D&reserved=0>.
