### ISSUE TITLE
Unexpected numerical result, large difference between matrix and clifford method

### ISSUE THREAD

**Issue by kaluzaklein** [pygae/clifford#416]
```python
from clifford.g3 import *
import math
from math import pi, e
import numpy as np

theta_deg = 135.0
L_deg = 30.0
theta_rad = theta_deg/180.0*math.pi
L_rad = L_deg/180.0*math.pi
R_theta = math.e**(-(e1^e2)*theta_rad*0.5)
R_L = math.e**(-(e3^e1)*(pi/2.0 - L_rad)*0.5)
# Convert to the matrix method for comparison
A = [e1,e2,e3]
B = [~R_L * ~R_theta * a * R_theta * R_L for a in A]
M = [float(b|a) for b in B for a in A] # you need float() due to bug in clifford
M = np.array(M).reshape(3,3)
print(M)  # This shows the correct expected result
x = np.array([[2.0],[-1.0],[1.5]])
print("Matrix mult result = " + str(np.matmul(M,x)))  # this also shows the expected result
x_sez = 2.0*e1 - 1.0*e2 + 1.5*e3
print("x_sez = " + str(x_sez))
print(~R_L * ~R_theta * x_sez * R_theta * R_L)  # This gives an unexpected result
```

 Code output:
```
[[-3.53553391e-01 -7.07106781e-01 -6.12372436e-01]
 [ 3.53553391e-01 -7.07106781e-01  6.12372436e-01]
 [-8.66025404e-01 -2.40370336e-17  5.00000000e-01]]
Matrix mult result = [[-0.91855865]
 [ 2.33277222]
 [-0.98205081]]
x_sez = (2.0^e1) - (1.0^e2) + (1.5^e3)
-(2.3597^e1) - (0.70711^e2) - (1.08712^e3)
```
The "Matrix mult result" is what I expect. The clifford/rotor result `(-(2.3597^e1) - (0.70711^e2) - (1.08712^e3))` is not what I expect. They should be equal. Am I making some syntax error?

**Comment by kaluzaklein** [comment]
I get the correct answer when I compute this instead:
`R_theta * R_L * x * ~R_L * ~R_theta`
In retrospect, I was thinking about the direction of the transformation incorrectly.

However, now it looks like the matrix form is giving the unexpected result (it is the transpose of what I would expect) given the rotor order that I gave it.

**Comment by kaluzaklein** [comment]
Reopening issue because the Matrix equivalence documentation seems suspect (returning the transpose of the right answer)

**Comment by eric-wieser** [comment]
I think you're right, this is a documentation mistake. I've opened #417, which transposes the matrix in the example.
