### ISSUE TITLE
Finish algebra generation optimisation

### ISSUE THREAD

**Issue by hugohadfield** [pygae/clifford#54]
There is still quite a bit of low hanging fruit performance-wise around the algebra generation setup. Currently we swap between tuples of grades, bitmaps and indices into the mv value array pretty liberally, eliminating this and jitting the remaining functions would allow us to speed up the generation quite a lot as well as allowing us to lean on the automatic parallelisation capabilities in numba and potentially even adding a cuda generation option.

Additionally @enkimute has suggested a nice loop free bitcount method that could add additional performance:
https://github.com/enkimute/ganja.js/issues/17#issuecomment-423962512

**Comment by eric-wieser** [comment]
> Currently we swap between tuples of grades, bitmaps and indices into the mv value array pretty liberally, eliminating this and ...

This is mostly done in #273

**Comment by eric-wieser** [comment]
Instead of using @enkimute's optimization, we now just use `__builtin_popcnt` which might even turn into a single assembly instruction.
