### ISSUE TITLE
Citing this library

### ISSUE THREAD

**Issue by hugohadfield** [pygae/clifford#55]
I am working on some reports/papers that will need to cite this package, we should come up with some strategy for this... my current plan:
```
@Misc{clifford_python,
author =   "{The Pygae Team}",
title =    {clifford: Numerical geometric algebra module for python},
howpublished = {\url{https://github.com/pygae/clifford}}
}
```
Any opinions?

**Comment by moble** [comment]
That looks reasonable.  Another trend that I'm seeing lately is people archiving significant releases to zenodo, figshare, etc.  (For my money, zenodo is the *clear* winner, as it's got long-term funding from the EU, and is basically part of CERN, which will need massive storage and usability for decades.  Plus it's free.  I've uploaded ~7TB of data to zenodo, and it's working great.  There's a github guide for it [here](https://guides.github.com/activities/citable-code/).)  The main benefit is that it provides a DOI and an archival copy of the exact code you're citing.  I'm not saying github's new ownership is necessarily gonna send things the way of the Zune, but stranger things have happened.

**Comment by moble** [comment]
Another thing I think would be good is if Alex and you (Hugo) are explicitly listed as authors.  It's certainly clear that Alex is the primary author, having created it, built its basic structure, and maintained it all this time.  And at this point, Hugo has also done a very large amount of work on the code, with a significant gap to the next-highest contributor.  You both deserve clear credit for it, and it may be helpful in, e.g., job applications, convincing thesis committees that you're personally doing work, etc.  My frame of reference is the analogy of authorship on a journal article, and for comparable contributions to an article I would think that you two would be authors while Jacopo would get a mention in the acknowledgments.

**Comment by arsenovic** [comment]
this is ok with me.  however,  for the record robert kern is the original author, so we should keep his name  on it too.  i migrated the project from some other version control service, and i think this is inflating my  commit volume.

**Comment by hugohadfield** [comment]
Ok cool, thanks for the info @moble, I think zenodo looks very cool and I'll have a go at setting it up today!

**Comment by hugohadfield** [comment]
Ok in order to do this we will need a new release.. I will tag the latest master and release that, I think it contains enough new and interesting stuff to be a worthwhile release :+1:

**Comment by hugohadfield** [comment]
Annoyingly it looks like you can't release to zenodo via pushing tags, so will do a separate archive release...

**Comment by hugohadfield** [comment]
We are up on zenodo :) and I'll go with this for now
```
@misc{clifford_python_v101, 
title={pygae/clifford: v1.0.1}, 
DOI={10.5281/zenodo.1453979}, 
abstractNote={Numerical geometric algebra module for python}, 
publisher={Zenodo},
author={Alex Arsenovic and Hugo Hadfield and Robert Kern and "The Pygae Team"}, 
year={2018}, month={Oct}}
```

**Comment by hugohadfield** [comment]
Time to bring this back and add @eric-wieser as an author as well I think! On that note I can't work out how to get zenodo to display its `cite as' section correctly

**Comment by eric-wieser** [comment]
In case we forget and come back here - we should add a `.zenodo.json` file with author information to the root of the repo.

**Comment by hugohadfield** [comment]
This is now done in: https://github.com/pygae/clifford/pull/288
