### ISSUE TITLE
rotors blow up for large angles

### ISSUE THREAD

**Issue by arsenovic** [pygae/clifford#67]
this blows up  for euclidean e12
```
theta = linspace(0,20*pi,101)
[e**(t*e12) for t in theta]
```

**Comment by hugohadfield** [comment]
I have a fix, will bring it in in a few mins

**Comment by hugohadfield** [comment]
This should fix it:
https://github.com/pygae/clifford/pull/66/commits/b409897c2673d0fe3976ebac429a5662b0feb2ab
