### ISSUE TITLE
Run test suite from installed package

### ISSUE THREAD

**Issue by esc** [pygae/clifford#91]
After installing the package from conda-forge, is it possible to run the test-suite?

**Comment by arsenovic** [comment]
yeah i think its `nosetests test/test_clifford.py` , there are other tests in there too.

**Comment by hugohadfield** [comment]
huh, I actually have no idea if you can do it from just an installation, I guess we would have to package the tests into the package with our setup.py right? Will have a look into it

**Comment by arsenovic** [comment]
woops, my bad, i mislead you. yeah i think you are right hugo.

**Comment by esc** [comment]
Yes, this is possible and can make sense. For example, it would allow your users to test the installation and make sure that everything is fine. It might not make sense though, if you need to generated gigabytes of data or if your test suite includes such large data since it would bloat the package. For example, the blosc package has it setup so that you can do:

```
$ python -c "import blosc; blosc.test()"
```

And the HPAT package  allows for:

```
python -m hpat.runtests
```

**Comment by hugohadfield** [comment]
I think this is definitely worthwhile, our tests sometimes take a long time to run but they also have granularity so could be run in chunks, would essentially involve moving our runner test directory into the main package and making a convenience function for it..

**Comment by esc** [comment]
The reason I was asking about this, is because I have been working on an integration-testing suite to check clifford against the latest Numba master. This acts as an early warning system for the Numba developers and will allow us to see if we are breaking anything:

https://github.com/numba/numba-integration-testing

If you do add support for running the tests from an installed package do let me know and I'll update that test-suite.

**Comment by esc** [comment]
Also, this isn't strictly required for the testing, so feel free to close this issue if it's not of interest to you.

**Comment by hugohadfield** [comment]
@esc sorry for the late reply, I got swamped by paper deadlines and moving house etc. I'm really pleased we are part of the integration testing for numba :) and will have a look at moving the test suite into the package (also ensuring all our tests pass..)

**Comment by eric-wieser** [comment]
https://github.com/numba/numba-integration-testing/pull/28 is somewhat relevant here
