### ISSUE TITLE
Errors on PerformanceCliffordTutorial

### ISSUE THREAD

**Issue by cdeil** [pygae/clifford#93]
There's currently errors on https://clifford.readthedocs.io/en/latest/PerformanceCliffordTutorial.html 

`AttributeError: 'Layout' object has no attribute 'gmt'`

Needs a fix?

Screenshot:

![Screenshot 2019-05-07 at 18 34 21](https://user-images.githubusercontent.com/852409/57316744-cde34480-70f6-11e9-920c-eeacfefd90b9.png)

**Comment by hugohadfield** [comment]
Yes it does, apologies! It is a bit out of date due to some overhauls of the internals of the library a while ago

**Comment by eric-wieser** [comment]
#138 fixes this error, but introduces a new one: https://external-builds.readthedocs.io/html/clifford/138/PerformanceCliffordTutorial.html

(note this link may become stale)

![image](https://user-images.githubusercontent.com/425260/67009488-a51e9c80-f0e3-11e9-9073-d60b3b7a4a91.png)

`AttributeError: 'Layout' object has no attribute 'omt'`

**Comment by eric-wieser** [comment]
Fixed in gh-140
