### ISSUE TITLE
Build and release wheel files

### ISSUE THREAD

**Issue by hugohadfield** [pygae/clifford#96]
We should build and upload wheel files with our releases, would allow us to be hosted on pyiodide
https://alpha.iodide.io/notebooks/2805/

**Comment by eric-wieser** [comment]
Unfortunately this just punts the iodide problem to numba:

![image](https://user-images.githubusercontent.com/425260/69147598-4aa1a300-0aca-11ea-836a-a0af1e99000c.png)

**Comment by eric-wieser** [comment]
Closing this in favor of #208
